version: 0.2.1
baudrate: 4000000
port: /dev/ttyUSB1 # linux
# port: /dev/tty.usbserial-FT9MISJT # mac
max_current: 400

type: left

# current, velocity, position, multi-turn- position, current_based_position
control_mode: current_based_position

motor_ids: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17]
joint_ids: [thumb_mcp, thumb_abd, thumb_pip, thumb_dip, index_abd, index_mcp, index_pip, middle_abd, middle_mcp, middle_pip, ring_abd, ring_mcp, ring_pip, pinky_abd, pinky_mcp, pinky_pip, wrist]

# Which motor ID is physically connected to which joint
joint_to_motor_map:
  thumb_mcp: 1
  thumb_abd: 2
  thumb_pip: 3
  thumb_dip: 4
  index_abd: 5
  index_mcp: 6
  index_pip: 7
  middle_abd: 8
  middle_mcp: 9
  middle_pip: 10
  ring_abd: -11
  ring_mcp: 12
  ring_pip: 13
  pinky_abd: 14
  pinky_mcp: 15
  pinky_pip: 16
  wrist: 17

joint_roms:
  thumb_mcp: [-50, 50]
  thumb_abd: [-20, 42]
  thumb_pip: [-12, 108]
  thumb_dip: [-20, 112]
  index_abd: [-37, 37]
  index_mcp: [-20, 95]
  index_pip: [-20, 108]
  middle_abd: [-37, 37]
  middle_mcp: [-20, 91]
  middle_pip: [-20, 107]
  ring_abd: [-37, 37]
  ring_mcp: [-20, 91]
  ring_pip: [-20, 107]
  pinky_abd: [-37, 37]
  pinky_mcp: [-20, 98]
  pinky_pip: [-20, 108]
  wrist: [-50, 30]



neutral_position:
  thumb_mcp: -13
  thumb_abd: 43
  thumb_pip: 33
  thumb_dip: 19
  index_abd: 25
  index_mcp: 0
  index_pip: 0
  middle_abd: -2
  middle_mcp: 0
  middle_pip: 0
  ring_abd: -20
  ring_mcp: -1
  ring_pip: 0
  pinky_abd: -55
  pinky_mcp: 1
  pinky_pip: 0
  wrist: 0

# joint_roms:
#   thumb_mcp: [-50, 80]
#   thumb_abd: [-50, 50]
#   thumb_pip: [-50, 80]
#   thumb_dip: [-50, 80]
#   index_abd: [-50, 50]
#   index_mcp: [-50, 80]
#   index_pip: [-50, 80]
#   middle_abd: [-50, 50]
#   middle_mcp: [-50, 80]
#   middle_pip: [-50, 80]
#   ring_abd: [-50, 50]
#   ring_mcp: [-50, 80]
#   ring_pip: [-50, 80]
#   pinky_abd: [-50, 50]
#   pinky_mcp: [-50, 80]
#   pinky_pip: [-50, 80]
#   wrist: [-50, 50]

# neutral_position:
#   thumb_mcp: -40
#   thumb_abd: 3
#   thumb_pip: -15
#   thumb_dip: -35
#   index_abd: -3
#   index_mcp: -15
#   index_pip: -20
#   middle_abd: -7
#   middle_mcp: -8
#   middle_pip: -26
#   ring_abd: 0
#   ring_mcp: -7
#   ring_pip: -30
#   pinky_abd: -3
#   pinky_mcp: -7
#   pinky_pip: -20
#   wrist: 0

calib_current: 400
calib_step_size: 0.1
calib_step_period: 0.001
calib_num_stable: 10  # should be period * num_stable > 1
calib_threshold: 0.01

calib_sequence:
  - step: 1
    joints:
      thumb_mcp: flex
  - step: 2
    joints:
      thumb_mcp: extend
  - step: 3
    joints:
      thumb_abd: flex
  - step: 4
    joints:
      thumb_abd: extend
  - step: 5
    joints:
      thumb_pip: flex
  - step: 6
    joints:
      thumb_pip: extend
  - step: 7
    joints:
      thumb_dip: flex
  - step: 8
    joints:
      thumb_dip: extend
  - step: 9
    joints:
      index_abd: flex
      middle_abd: flex
      ring_abd: flex
      pinky_abd: flex
  - step: 10
    joints:
      index_abd: extend
      middle_abd: extend
      ring_abd: extend
      pinky_abd: extend
  - step: 11
    joints:
      index_mcp: flex
  - step: 12
    joints:
      index_mcp: extend
  - step: 13
    joints:
      index_pip: flex
  - step: 14
    joints:
      index_pip: extend
  - step: 15
    joints:
      middle_mcp: flex
  - step: 16
    joints:
      middle_mcp: extend
  - step: 17
    joints:
      middle_pip: flex
  - step: 18
    joints:
      middle_pip: extend
  - step: 19
    joints:
      ring_mcp: flex
  - step: 20
    joints:
      ring_mcp: extend
  - step: 21
    joints:
      ring_pip: flex
  - step: 22
    joints:
      ring_pip: extend
  - step: 23
    joints:
      pinky_mcp: flex
  - step: 24
    joints:
      pinky_mcp: extend
  - step: 25
    joints:
      pinky_pip: flex
  - step: 26
    joints:
      pinky_pip: extend
  - step: 27
    joints:
      wrist: flex
  - step: 28
    joints:
      wrist: extend

# calib_sequence:
#   - step: 1
#     joints:
#       pinky_pip: flex
#   - step: 2
#     joints:
#       pinky_pip: extend
    
